### ISSUE TITLE
MaterialDesignIcons do not work

### ISSUE THREAD

**Issue by nstrelow** [JHBitencourt/timeline_tile#14]
I am using https://pub.dev/packages/material_design_icons_flutter to have more icons.

Sadly it breaks. No idea why.

Probably somehow related to the way the font is acquired.

Using a custom indicator now.

```dart
indicatorStyle: IndicatorStyle(
                          width: 40,
                          color: Colors.purple,
                          padding: const EdgeInsets.all(8),
                          iconStyle: IconStyle(
                            color: Colors.white,
                            iconData: MdiIcons.delete,
                          ),
                        ),
```

![image](https://user-images.githubusercontent.com/1096841/91226255-090eea00-e725-11ea-9a79-f5de3ff9522b.png)

**Comment by JHBitencourt** [comment]
Thanks for the issue @nstrelow.

Well, the cause of this problem is that when using a default `iconData` I'm painting it directly on Canvas with `ui.ParagraphBuilder` as you can see [here](https://github.com/JHBitencourt/timeline_tile/blob/master/lib/src/tile.dart#L373).

```dart
final builder = ui.ParagraphBuilder(ui.ParagraphStyle(
  fontFamily: iconData.fontFamily,
));
```

So the `fontFamily` is required. When using the default flutter `Icons` it defines the `fontFamily` as `MaterialIcons` that is by default loaded by the SDK.

The `material_design_icons_flutter` package defines a custom font (as you can see on its [implementation](https://github.com/ziofat/material_design_icons_flutter/blob/master/lib/material_design_icons_flutter.dart#L5507)) that `ui.ParagraphBuilder` is not aware of.

So at this point you have 2 options:
1. Use a custom indicator with these custom icons
2. Define the custom font in your `pubspec.yaml` so that `ui.ParagraphBuilder` will recognise and know how to paint it on canvas.

For this last option you need to take the custom `.ttf` [file](https://github.com/ziofat/material_design_icons_flutter/tree/master/lib/fonts) and put it into your `assets/fonts` folder. Now you can declare it into your `pubspec.yaml`:

```yaml
flutter:
  uses-material-design: true

  fonts:
    - family: Material Design Icons
      fonts:
        - asset: assets/fonts/materialdesignicons-webfont.ttf
```

With this you'll be able to use `MdiIcons` (or any other custom icons package) with the default indicator.

Let me know if this help you.

**Comment by JHBitencourt** [comment]
I'm closing this issue, due to inactivity from the creator.

And the solution can be achieved as explained in my previous comment.

**Comment by nstrelow** [comment]
I think in the end I ended up using a custom indicator.

Thanks anyway 👍
