### ISSUE TITLE
Custom indicator with package avatar_glow?

### ISSUE THREAD

**Issue by nholmvio** [JHBitencourt/timeline_tile#20]
Thanks for this great package..

Is there any reason animation on an indicator should not work?  For example i'm using  avatar_glow (from pub.dev) to wrap a custom indicator and i'm unable to get the indicator to pulse (able to have avatar_glow working elsewhere).

Should there be any reason that does not work wrapping indicator?

Thank you.

**Comment by JHBitencourt** [comment]
Hey, thanks for making contact.

About the issue, can you provide some code not working?
Because I have just tested this package with custom indicator and is working just fine.
Remember that, you must provide enough space in the indicator (`height`/`width`) so that the radius animation used in `avatar_glow ` can appear.

```dart
TimelineTile(
  alignment: TimelineAlign.center,
  indicatorStyle: IndicatorStyle(
    width: 80,
    height: 80,
    indicator: AvatarGlow(
      glowColor: Colors.red,
      endRadius: 45.0,
      child: Material(
        elevation: 8.0,
        shape: CircleBorder(),
        child: CircleAvatar(
          backgroundColor: Colors.grey[100],
          child: Image.asset(
            'assets/hitchhiker.png',
            height: 20,
          ),
          radius: 20.0,
        ),
      ),
    ),
  ),
),
```

Let me know if it doesn't help you.

**Comment by nholmvio** [comment]
Ah...Yes that was it!  i was not leaving enough from in the indicator height/width for the animation to be visible.

Thank you for the prompt reply and fantastic support!  And again, thanks for great package.
